export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOAD_FIRESTORE_DATA = "LOAD_FIRESTORE_DATA";
export const GET_WHOLE_STATE = "GET_WHOLE_STATE";
export const TRIGGER_RELOAD = "TRIGGER_RELOAD";
export const SETNOTIFICATION = "SETNOTIFICATION"
export const REFRESHTOKENS = "REFRESHTOKENS";
export const UPDATETRAVELSTATUS = 'UPDATEUPCOMMINGTRAVEL';
